window.FACTORY_FLOW_LEVELS = [
  {"title":"Première ligne","objective":"Traite 4 pièces rouges.","queue":"RRRR","buffer":0,"machines":{"R":{"processing":0}},"hint":"La machine rouge accepte uniquement les pièces rouges."},
  {"title":"Deux postes","objective":"Traite les rouges et les bleues.","queue":"RBBRRB","buffer":0,"machines":{"R":{"processing":0},"B":{"processing":0}},"hint":"Lis la couleur de la première pièce puis touche la machine correspondante."},
  {"title":"Cycle machine","objective":"Apprends à gérer une machine occupée.","queue":"RRBRB","buffer":1,"machines":{"R":{"processing":1},"B":{"processing":0}},"hint":"Quand la machine rouge travaille, stocke temporairement une pièce ou traite une autre couleur."},
  {"title":"Le buffer","objective":"Utilise le buffer sans saturer la ligne.","queue":"RRBBRB","buffer":2,"machines":{"R":{"processing":2},"B":{"processing":0}},"hint":"Le buffer change l’ordre de traitement. Sélectionne ensuite une pièce stockée pour la réinjecter."},
  {"title":"Séquence tendue","objective":"Évite le blocage avec seulement 2 places.","queue":"RRRBBRBB","buffer":2,"machines":{"R":{"processing":2},"B":{"processing":1}},"hint":"Ne remplis pas le buffer trop tôt : garde une place pour une pièce vraiment bloquante."},
  {"title":"Troisième couleur","objective":"Coordonne trois machines.","queue":"RYYBRYBBY","buffer":3,"machines":{"R":{"processing":1},"B":{"processing":1},"Y":{"processing":2}},"hint":"Tu peux traiter une pièce du buffer pendant que la pièce d’entrée attend."},
  {"title":"Maintenance","objective":"La machine bleue démarre en maintenance.","queue":"BBRYRBY","buffer":3,"machines":{"R":{"processing":1},"B":{"processing":1,"maintenance":2},"Y":{"processing":1}},"hint":"Au début, les bleues doivent attendre : libère de la place avec les autres couleurs."},
  {"title":"Goulot jaune","objective":"La machine jaune est le goulot.","queue":"YYRBYRYBY","buffer":3,"machines":{"R":{"processing":1},"B":{"processing":1},"Y":{"processing":3}},"hint":"Le poste jaune est lent. Évite d’accumuler les jaunes au mauvais moment."},
  {"title":"Ligne mixte","objective":"Quatre postes, buffer limité.","queue":"GRBYGGRYBBYG","buffer":3,"machines":{"R":{"processing":1},"B":{"processing":2},"Y":{"processing":2},"G":{"processing":1}},"hint":"Observe plusieurs pièces à l’avance et protège toujours une place de buffer."},
  {"title":"Challenge usine","objective":"Optimise la ligne complète sans la bloquer.","queue":"RBYGRRYYBBGGRYB","buffer":3,"machines":{"R":{"processing":2},"B":{"processing":2},"Y":{"processing":3},"G":{"processing":1,"maintenance":1}},"hint":"Pense en flux : machine lente = priorité d’anticipation, buffer = sécurité, pas stockage permanent."}
];
